#!/bin/bash
set -e
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
	if command -v systemctl >/dev/null 2>&1; then
		systemctl stop buscalogo-registry.service >/dev/null 2>&1 || true
	fi
fi
#DEBHELPER#
